# Generated by Django 6.0.3 on 2026-04-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0004_phongtro_nguoi_thich'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhAnhPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(upload_to='phongtro_chitiet/')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_hinh_anh', to='quanly.phongtro')),
            ],
        ),
    ]
